#!/usr/bin/env python3
"""
Dymola launcher for agent skills.

Discovers a Dymola installation, writes a ``.mos`` script, and runs Dymola
headlessly (``/nowindow``) to validate, translate, simulate, or export
exposed parameters — including public parameters from encrypted libraries.

Environment overrides:
  DYMOLA_HOME       Install root (folder containing bin/Dymola.exe)
  DYMOLA_EXE        Full path to Dymola executable
  DYMOLA_MODELICAPATH  Extra Modelica library paths (os.pathsep-separated)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import List, Optional, Sequence, Tuple


def _win():
    return sys.platform.startswith("win")


def discover_dymola(explicit: Optional[str] = None) -> Tuple[Path, Path]:
    """Return (install_root, exe_path)."""
    if explicit:
        p = Path(explicit)
        if p.is_file():
            return p.parent.parent if p.parent.name.lower() == "bin" else p.parent, p
        exe = _exe_in_root(p)
        if exe:
            return p, exe
        raise FileNotFoundError(f"No Dymola executable under --dymola-home {p}")

    env_exe = os.environ.get("DYMOLA_EXE")
    if env_exe and Path(env_exe).is_file():
        exe = Path(env_exe)
        root = exe.parent.parent if exe.parent.name.lower() == "bin" else exe.parent
        return root, exe

    env_home = os.environ.get("DYMOLA_HOME") or os.environ.get("DYMOLAINSTALL")
    if env_home:
        root = Path(env_home)
        exe = _exe_in_root(root)
        if exe:
            return root, exe

    candidates: List[Path] = []
    if _win():
        for base in filter(None, [
            os.environ.get("ProgramFiles"),
            os.environ.get("ProgramFiles(x86)"),
            r"C:\Program Files",
            r"C:\Program Files (x86)",
        ]):
            base_p = Path(base)
            if base_p.is_dir():
                candidates.extend(sorted(base_p.glob("Dymola*"), reverse=True))
                candidates.extend(sorted(base_p.glob("Dassault Systemes/Dymola*"), reverse=True))
    else:
        for pattern in ("/opt/dymola*", "/usr/local/dymola*", str(Path.home() / "dymola*")):
            candidates.extend(sorted(Path("/").glob(pattern.lstrip("/")), reverse=True) if pattern.startswith("/opt") else [])
            candidates.extend(sorted(Path(p) for p in Path("/").glob(pattern[1:]) if False))
        candidates.extend(sorted(Path("/opt").glob("dymola*"), reverse=True))
        candidates.extend(sorted(Path("/usr/local").glob("dymola*"), reverse=True))
        candidates.extend(sorted(Path.home().glob("dymola*"), reverse=True))

    for root in candidates:
        exe = _exe_in_root(root)
        if exe:
            return root, exe

    # PATH fallback
    for name in ("Dymola.exe", "dymola.exe", "dymola"):
        found = shutil.which(name)
        if found:
            exe = Path(found)
            root = exe.parent.parent if exe.parent.name.lower() == "bin" else exe.parent
            return root, exe

    raise FileNotFoundError(
        "Could not locate a Dymola installation. Set DYMOLA_HOME or pass --dymola-home."
    )


def _exe_in_root(root: Path) -> Optional[Path]:
    names = ("Dymola.exe", "dymola.exe", "Dymola", "dymola")
    for sub in ("bin", "Bin", ""):
        base = root / sub if sub else root
        for n in names:
            p = base / n
            if p.is_file():
                return p
    return None


def mos_escape(path: Path) -> str:
    """Modelica string path with forward slashes."""
    return str(path.resolve()).replace("\\", "/")


def write_mos(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body.strip() + "\n", encoding="utf-8")
    return path


def build_validate_mos(
    model_path: Path,
    model_name: str,
    *,
    load_libs: Sequence[Path] = (),
    result_json: Path,
) -> str:
    loads = "\n".join(f'openModel("{mos_escape(p)}");' for p in load_libs)
    return textwrap.dedent(
        f"""\
        // Auto-generated by dymola_run.py — validate
        Advanced.TranslationInCommandLog = true;
        {loads}
        okOpen = openModel("{mos_escape(model_path)}");
        okCheck = checkModel({model_name});
        writeFile("{mos_escape(result_json)}",
          "{{\\"mode\\":\\"validate\\",\\"open\\":" + String(okOpen) +
          ",\\"check\\":" + String(okCheck) + "}}");
        savelog("{mos_escape(result_json.with_suffix('.log'))}");
        exit();
        """
    )


def build_translate_mos(
    model_path: Path,
    model_name: str,
    workdir: Path,
    *,
    load_libs: Sequence[Path] = (),
    result_json: Path,
    export_params: bool = True,
) -> str:
    loads = "\n".join(f'openModel("{mos_escape(p)}");' for p in load_libs)
    # translateModel writes dymosim + dsin.txt into cwd; we cd via chdir in launcher
    export = ""
    if export_params:
        # Dump public component modifiers / parameters via scripting where available.
        # Fallback surface is always dsin.txt after a successful translate.
        export = textwrap.dedent(
            f"""\
            // Prefer dsin.txt as the exposed-parameter catalog (works with encrypted libs).
            // Also attempt a Modelica-side listing when the command exists.
            """
        )
    return textwrap.dedent(
        f"""\
        // Auto-generated by dymola_run.py — translate
        Advanced.TranslationInCommandLog = true;
        cd("{mos_escape(workdir)}");
        {loads}
        okOpen = openModel("{mos_escape(model_path)}");
        okTrans = translateModel({model_name});
        {export}
        writeFile("{mos_escape(result_json)}",
          "{{\\"mode\\":\\"translate\\",\\"open\\":" + String(okOpen) +
          ",\\"translate\\":" + String(okTrans) +
          ",\\"workdir\\":\\"{mos_escape(workdir)}\\"}}");
        savelog("{mos_escape(result_json.with_suffix('.log'))}");
        exit();
        """
    )


def build_simulate_mos(
    model_path: Path,
    model_name: str,
    workdir: Path,
    *,
    load_libs: Sequence[Path] = (),
    stop_time: Optional[float] = None,
    result_json: Path,
    result_file: str = "dsres.mat",
) -> str:
    loads = "\n".join(f'openModel("{mos_escape(p)}");' for p in load_libs)
    sim_args = f'{model_name}, resultFile="{result_file}"'
    if stop_time is not None:
        sim_args = f"{model_name}, stopTime={stop_time}, resultFile=\"{result_file}\""
    return textwrap.dedent(
        f"""\
        // Auto-generated by dymola_run.py — simulate
        Advanced.TranslationInCommandLog = true;
        cd("{mos_escape(workdir)}");
        {loads}
        okOpen = openModel("{mos_escape(model_path)}");
        okSim = simulateModel({sim_args});
        writeFile("{mos_escape(result_json)}",
          "{{\\"mode\\":\\"simulate\\",\\"open\\":" + String(okOpen) +
          ",\\"simulate\\":" + String(okSim) +
          ",\\"result\\":\\"{result_file}\\",\\"workdir\\":\\"{mos_escape(workdir)}\\"}}");
        savelog("{mos_escape(result_json.with_suffix('.log'))}");
        exit();
        """
    )


def build_list_params_mos(
    model_path: Path,
    model_name: str,
    workdir: Path,
    *,
    load_libs: Sequence[Path] = (),
    result_json: Path,
) -> str:
    """
    Translate so Dymola emits dsin.txt (public + exposed encrypted parameters),
    then exit. The Python side parses dsin.txt — no decryption involved.
    """
    return build_translate_mos(
        model_path,
        model_name,
        workdir,
        load_libs=load_libs,
        result_json=result_json,
        export_params=True,
    )


def run_dymola(
    exe: Path,
    mos: Path,
    *,
    timeout: int = 300,
    extra_args: Sequence[str] = (),
) -> subprocess.CompletedProcess:
    # Headless flags differ slightly by version; /nowindow is widely supported on Windows.
    cmd = [str(exe)]
    if _win():
        cmd.append("/nowindow")
    else:
        cmd.append("-nowindow")
    cmd.extend(extra_args)
    cmd.append(str(mos))
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
    )


def find_dymosim(workdir: Path) -> Optional[Path]:
    for name in ("dymosim.exe", "dymosim"):
        p = workdir / name
        if p.is_file():
            return p
    return None


def run_dymosim(
    dymosim: Path,
    *,
    dsin: Optional[Path] = None,
    workdir: Optional[Path] = None,
    timeout: int = 300,
) -> subprocess.CompletedProcess:
    """
    Run a compiled simulation binary.

    Convention: place / point at dsin.txt beside dymosim; many builds accept
    ``dymosim -s`` to simulate using dsin.txt in the cwd.
    """
    cwd = str(workdir or dymosim.parent)
    if dsin is not None:
        target = Path(cwd) / "dsin.txt"
        if Path(dsin).resolve() != target.resolve():
            shutil.copy2(dsin, target)
    cmd = [str(dymosim), "-s"]
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
    )


def infer_model_name(model_path: Path, explicit: Optional[str] = None) -> str:
    if explicit:
        return explicit
    text = model_path.read_text(encoding="utf-8", errors="replace")
    # Strip block comments roughly
    text_nc = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    m = re.search(r"\b(model|class|block|connector|record|function|package)\s+('(?:\\'|[^'])+'|[A-Za-z_]\w*)", text_nc)
    if m:
        return m.group(2).strip("'")
    return model_path.stem


def mode_info(dymola_home: Optional[str]) -> dict:
    root, exe = discover_dymola(dymola_home)
    return {
        "dymola_home": str(root),
        "dymola_exe": str(exe),
        "platform": sys.platform,
        "modelicapath": os.environ.get("DYMOLA_MODELICAPATH") or os.environ.get("MODELICAPATH") or "",
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Run Dymola headlessly for agent skills")
    ap.add_argument("--mode", required=True,
                    choices=["info", "validate", "translate", "simulate", "list-params", "run-dymosim"])
    ap.add_argument("--model", help="Path to .mo file or library package.mo / folder")
    ap.add_argument("--name", help="Modelica class name (dotted ok)")
    ap.add_argument("--load", action="append", default=[], help="Extra .mo / package.mo to open first")
    ap.add_argument("--tempdir", help="Working directory (default: <model-dir>/_dymola_<mode>_temp)")
    ap.add_argument("--dymola-home", default=None)
    ap.add_argument("--timeout", type=int, default=300)
    ap.add_argument("--stop-time", type=float, default=None)
    ap.add_argument("--dymosim", help="Path to dymosim.exe (run-dymosim mode)")
    ap.add_argument("--dsin", help="dsin.txt to use with run-dymosim")
    ap.add_argument("--override", default=None, help="For run-dymosim: name=val,name2=val2 applied to dsin")
    ap.add_argument("--json", action="store_true", help="Print machine-readable summary")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(list(argv) if argv is not None else None)

    if args.mode == "info":
        try:
            info = mode_info(args.dymola_home)
            print(json.dumps(info, indent=2) if args.json else
                  f"Dymola home: {info['dymola_home']}\nExecutable: {info['dymola_exe']}")
            return 0
        except FileNotFoundError as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2

    try:
        root, exe = discover_dymola(args.dymola_home)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    if args.mode == "run-dymosim":
        from dsin_io import parse_dsin, parse_override_string, set_parameters, write_dsin

        dymosim = Path(args.dymosim) if args.dymosim else None
        if dymosim is None or not dymosim.is_file():
            print("ERROR: --dymosim path required and must exist", file=sys.stderr)
            return 2
        workdir = Path(args.tempdir) if args.tempdir else dymosim.parent
        workdir.mkdir(parents=True, exist_ok=True)
        dsin_path = Path(args.dsin) if args.dsin else (workdir / "dsin.txt")
        if not dsin_path.is_file():
            print(f"ERROR: dsin not found: {dsin_path}", file=sys.stderr)
            return 2
        if args.override:
            dsin = parse_dsin(dsin_path)
            updated, applied, missing = set_parameters(dsin, parse_override_string(args.override))
            dsin_path = write_dsin(updated, workdir / "dsin.txt")
            if missing:
                print(f"WARNING: missing: {missing}", file=sys.stderr)
            if not args.quiet:
                print(f"Applied overrides: {applied}")
        t0 = time.time()
        cp = run_dymosim(dymosim, dsin=dsin_path, workdir=workdir, timeout=args.timeout)
        summary = {
            "mode": "run-dymosim",
            "returncode": cp.returncode,
            "elapsed_s": round(time.time() - t0, 3),
            "workdir": str(workdir),
            "dymosim": str(dymosim),
            "stdout_tail": (cp.stdout or "")[-2000:],
            "stderr_tail": (cp.stderr or "")[-2000:],
        }
        out_json = workdir / "run_dymosim.out.json"
        out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        print(json.dumps(summary, indent=2) if args.json else
              f"{'OK' if cp.returncode == 0 else 'FAIL'} dymosim rc={cp.returncode} ({summary['elapsed_s']}s) → {out_json}")
        return 0 if cp.returncode == 0 else 1

    if not args.model:
        print("ERROR: --model is required for this mode", file=sys.stderr)
        return 2
    model_path = Path(args.model)
    if model_path.is_dir():
        pkg = model_path / "package.mo"
        model_path = pkg if pkg.is_file() else model_path
    if not model_path.exists():
        print(f"ERROR: model not found: {args.model}", file=sys.stderr)
        return 2

    model_name = infer_model_name(model_path if model_path.is_file() else Path(args.model), args.name)
    model_dir = model_path.parent if model_path.is_file() else Path(args.model)
    workdir = Path(args.tempdir) if args.tempdir else (model_dir / f"_dymola_{args.mode.replace('-', '_')}_temp")
    if workdir.exists():
        shutil.rmtree(workdir, ignore_errors=True)
    workdir.mkdir(parents=True, exist_ok=True)

    load_libs = [Path(p) for p in args.load]
    result_json = workdir / f"{args.mode.replace('-', '_')}.out.json"
    mos_path = workdir / f"{args.mode.replace('-', '_')}.mos"

    if args.mode == "validate":
        body = build_validate_mos(model_path, model_name, load_libs=load_libs, result_json=result_json)
    elif args.mode in ("translate", "list-params"):
        body = build_list_params_mos(model_path, model_name, workdir, load_libs=load_libs, result_json=result_json)
    elif args.mode == "simulate":
        body = build_simulate_mos(
            model_path, model_name, workdir,
            load_libs=load_libs, stop_time=args.stop_time, result_json=result_json,
        )
    else:
        print(f"ERROR: unknown mode {args.mode}", file=sys.stderr)
        return 2

    write_mos(mos_path, body)
    if not args.quiet:
        print(f"Dymola: {exe}")
        print(f"Workdir: {workdir}")
        print(f"Running {args.mode} for {model_name} …")

    t0 = time.time()
    try:
        cp = run_dymola(exe, mos_path, timeout=args.timeout)
    except subprocess.TimeoutExpired:
        print(f"ERROR: Dymola timed out after {args.timeout}s", file=sys.stderr)
        return 3

    elapsed = round(time.time() - t0, 3)
    (workdir / "dymola_stdout.txt").write_text(cp.stdout or "", encoding="utf-8")
    (workdir / "dymola_stderr.txt").write_text(cp.stderr or "", encoding="utf-8")

    dsin = workdir / "dsin.txt"
    dymosim = find_dymosim(workdir)
    dsmodel = workdir / "dsmodel.c"
    summary = {
        "mode": args.mode,
        "model": str(model_path),
        "name": model_name,
        "dymola_exe": str(exe),
        "dymola_home": str(root),
        "workdir": str(workdir),
        "elapsed_s": elapsed,
        "returncode": cp.returncode,
        "result_json": str(result_json) if result_json.is_file() else None,
        "dsin": str(dsin) if dsin.is_file() else None,
        "dymosim": str(dymosim) if dymosim else None,
        "dsmodel_c": str(dsmodel) if dsmodel.is_file() else None,
        "log": str(result_json.with_suffix(".log")) if result_json.with_suffix(".log").is_file() else None,
    }

    # Enrich list-params with parameter count
    if args.mode == "list-params" and dsin.is_file():
        from dsin_io import parse_dsin
        parsed = parse_dsin(dsin)
        catalog = workdir / "exposed_parameters.json"
        catalog.write_text(
            json.dumps(
                {
                    "source": "dsin.txt",
                    "note": "Public/exposed simulation parameters emitted by Dymola after translate. Includes exposed parameters from encrypted components. No decryption performed.",
                    "count": len(parsed.entries),
                    "parameters": [
                        {"name": e.name, "value": e.value, "comment": e.comment, "section": e.section}
                        for e in parsed.entries
                    ],
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        summary["exposed_parameters"] = str(catalog)
        summary["parameter_count"] = len(parsed.entries)

    summary_path = workdir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"Done in {elapsed}s → {summary_path}")
        for k in ("dsin", "dymosim", "dsmodel_c", "exposed_parameters", "log"):
            if summary.get(k):
                print(f"  {k}: {summary[k]}")
    return 0 if cp.returncode == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
